defaults.url=https://sentry.infomaniak.com/
defaults.org=infomaniak
defaults.project=kmeet-electron
auth.token=88bdb619a0f246eba390f735d63fc9124f4ad856b4cb402c81d0fa1140f2047f
cli.executable=./node_modules/@sentry/cli/bin/sentry-cli
